version: 2
registries:
  getsupertab:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPMJS_READ_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    reviewers:
      - laterpay/clients-team
    schedule:
      interval: 'daily'
