version: 2
registries:
  getsupertab-npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPMJS_READ_TOKEN }}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - getsupertab-npm
    reviewers:
      - laterpay/clients-team
    schedule:
      interval: 'daily'
